[package]
name = "python-rust-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "python_rust_ffi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
dict_derive = "0.4.0"
